- name: Install dependencies
  apt:
    name: npm
    update_cache: yes
    state: present

- name: Download todo from Nexus
  get_url:
    url: http://172.31.9.76:8081/repository/todo/todo-0.0.1.zip
    dest: /root/todo
    username: admin
    password: momdad007

- name: Unzip the Downloaded Content
  unarchive:
    src: /root/todo
    dest: /root
    remote_src: yes

- name: Copy todos Service file
  copy:
    src: /root/todo.service
    dest: /etc/systemd/system/todo.service
    remote_src: yes

- name: Start todos Service
  systemd:
    name: todo
    daemon_reload: yes
    state: started
    enabled: yes